### PR TITLE
add pre-commit hooks; add issue-metrics workflow template

### PR DESCRIPTION
**Pull request by ghost**
Here's the background on this PR:

* wanted to get some metrics on doc-sig issues. 
  * found this github action: https://github.com/marketplace/actions/issue-metrics
  * deployed to doc-sig  [ex output](https://github.com/riscv-admin/docs-sig/issues/55)
* thought this could be useful to the whole org if they wanted to use it so added this as a workflow template
  * add pre-commit for linting since this adds coding

@wmat : not sure how to have this PR discussed/landed since I don't have any way to assign reviewer

### CODE REVIEW

**Comment by wmat** [comment]
My concern with Issue Metrics in general is that many issues, in particular in the docs-sig repo are placeholders/reminders of things we'd like to get done eventually.  So these will likely incur some poor metrics.  I'm unclear on what Issue Metrics is for?

**Comment by ghost** [comment]
> My concern with Issue Metrics in general is that many issues, in particular in the docs-sig repo are placeholders/reminders of things we'd like to get done eventually. So these will likely incur some poor metrics. I'm unclear on what Issue Metrics is for?

Agreed the overall stats are probably not that useful as is for doc-sig.  I do know that the `SEARCH_QUERY` can be changed to filter out issues to make overall stat's more usefull.  (and actually I need to add the `-reason:"not planned"` to this PR), but even if the overall metrics don't get there,  the feature I did like about this report is with the individual issue summary which isn't in https://github.com/riscv-admin/docs-sig/pulse/monthly

ex: 

| Title | URL | Author | Time to first response | Time to close | Time to answer |
| --- | --- | --- | --- | --- | --- |
| Listings caption | https://github.com/riscv-admin/docs-sig/issues/40 | [ved-rivos](https://github.com/ved-rivos) | 4 days, 3:05:14 | 5 days, 23:25:33 | None |

**Comment by wmat** [comment]
Cool, do you want to wait until you've added the not planned reason, or merge now?  Feel free to merge when ready.

**Comment by ghost** [comment]
> Cool, do you want to wait until you've added the not planned reason, or merge now? Feel free to merge when ready.

Done (snuck it in by squashing the commits).  I don't have any priv's to merge so please do.

**Pull request merged**
